--MEMBER 테이블 생성
CREATE TABLE MEMBER(
MENBER_ID NUMBER(20) NOT NULL PRIMARY KEY,
NAME VARCHAR2(20) NOT NULL,
RENGO CHAR(8) NOT NULL,
HP VARCHAR2(13) NOT NULL,
ADDRESS VARCHAR2(100) NOT NULL
);

DESC MEMBER;

--BOOK 테이블 생성
CREATE TABLE BOOK(
CODE NUMBER(4) NOT NULL PRIMARY KEY,
TITLE VARCHAR2(100) NOT NULL,
COUNT NUMBER(6) NOT NULL,
PRICE NUMBER(10) NOT NULL,
PUBLISH VARCHAR2(50) NOT NULL
);

DESC BOOK;

--데이터 타입 수정
ALTER TABLE MEMBER
MODIFY(MENBER_ID VARCHAR2(20));

--칼럼 이름 수정
ALTER TABLE MEMBER
RENAME COLUMN MENBER_ID TO MEMBER_ID;

--BOOR_ORDER 테이블 생성
CREATE TABLE BOOK_ORDER(
NO VARCHAR2(10) NOT NULL PRIMARY KEY,
ID VARCHAR2(20) NOT NULL,
CODE NUMBER(4) NOT NULL,
COUNT NUMBER(6) NOT NULL,
OR_DATE DATE NOT NULL
);

DESC BOOK_ORDER;

SELECT * FROM TAB;

--DEPT TABLE 생성
CREATE TABLE DEPT(
DEPTNO NUMBER(2),
DNAME VARCHAR2(14),
LOC VARCHAR2(13)
);

-- NULL -> NOT NULL 수정
ALTER TABLE DEPT
MODIFY DNAME NOT NULL
MODIFY LOC NOT NULL;

--데이터 삽입(INSERT INTO VALUES)
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(10, 'ACCOUNTING','NEW YORK');

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(15, 'COUNTING','PALIS');

--컬럼과 값의 수를 맞추지않음(NOT NULL);
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(15, 'COUNTING');

DESC DEPT;

SELECT * FROM DEPT;

--CREATE는 자동 COMMIT /INSERT는 메모리만 삽입되어있음 (CUMMIT X)

ROLLBACK; -- 데이터 삽입전으로 돌려짐
COMMIT; --데이터가 저장됨 //자바쪽에서 불러오기가 안될때 확인할 것
