------------------------------------------------

--무결성 제약조건 NOT NULL
DROP TABLE EMP01 PURGE;

CREATE TABLE EMP01(
EMPNO NUMBER(4) NOT NULL,
ENAME VARCHAR2(10) NOT NULL,
JOB VARCHAR2(9),
DEPTNO NUMBER(4)
);

--레코드 입력여부(NULL 불가)
INSERT INTO EMP01
VALUES (NULL,NULL,'SALESMAN',30);

INSERT INTO EMP01
VALUES (7499,'ALLEN','SALESMAN',30);

SELECT * FROM EMP01;

------------------------------------------------

--UNIQUE 선언

CREATE TABLE EMP02(
EMPNO NUMBER(4) UNIQUE,
ENAME VARCHAR2(10) NOT NULL,
JOB VARCHAR2(9),
DEPTNO NUMBER(4)
);

INSERT INTO EMP02(EMPNO,ENAME,JOB,DEPTNO)
VALUES(7499,'ALLEN','SALESMAN',30);

--동일한 사번을 입력해 오류생성
INSERT INTO EMP02(EMPNO,ENAME,JOB,DEPTNO)
VALUES(7499,'ALLEN','SALESMAN',30);

--EMPNO NOT NULL 입력
ALTER TABLE EMP02
MODIFY EMPNO NOT NULL;


DESC EMP02;

--NULL 값을 삽입하여 오류 생성
INSERT INTO EMP02(EMPNO,ENAME,JOB,DEPTNO)
VALUES(NULL,'JONES','MANAGER',20);

INSERT INTO EMP02(EMPNO,ENAME,JOB,DEPTNO)
VALUES(7500,'JONES','MANAGER',20);

--동일한 사번을 입력해 오류생성
INSERT INTO EMP02(EMPNO,ENAME,JOB,DEPTNO)
VALUES(7500,'JONES','MANAGER',20);

SELECT * FROM EMP02;
------------------------------------------------


